<?php require '../app/Views/header.phtml'; ?>

<div class="check-form">
    <form class="signup-form" action="/parameters/submit/" method="POST">
        <input id='step2' type='checkbox'>
        <input id='step3' type='checkbox'>
        <input id='step4' type='checkbox'>

        <?php if (isset($success)): ?>

            <div id="p1">
                <div class="panel">
                    <div class="panel-heading">
                        <h3>Uspjeh</h3>
                    </div>
                    <div id="success">&#10004;Nalaz uspješno zabilježen. Rezultate možete pogledati <a href="/result/index">ovdje</a>.</div>
                </div>
            </div>

        <?php elseif (isset($errors)):?>

            <div id="p1">
                <div class="panel">
                    <div class="panel-heading">
                        <h3>Registracija neuspješna</h3>
                    </div>
                    <?php if (isset($errors["bp-sys-notnumber"])): ?><label class="error-label">*<?php echo $errors["bp-sys-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["bp-dia-notnumber"])): ?><label class="error-label">*<?php echo $errors["bp-dia-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["rbc-notnumber"])): ?><label class="error-label">*<?php echo $errors["rbc-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["hemo-notnumber"])): ?><label class="error-label">*<?php echo $errors["hemo-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["su-notnumber"])): ?><label class="error-label">*<?php echo $errors["su-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["bu-notnumber"])): ?><label class="error-label">*<?php echo $errors["bu-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["sc-notnumber"])): ?><label class="error-label">*<?php echo $errors["sc-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["sod-notnumber"])): ?><label class="error-label">*<?php echo $errors["sod-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["pot-notnumber"])): ?><label class="error-label">*<?php echo $errors["pot-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["sg-notfloat"])): ?><label class="error-label">*<?php echo $errors["sg-notfloat"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["al-notnumber"])): ?><label class="error-label">*<?php echo $errors["al-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["wbcc-notnumber"])): ?><label class="error-label">*<?php echo $errors["wbcc-notnumber"]; ?></label><br> <?php endif; ?>
                    <?php if (isset($errors["rbcc-notnumber"])): ?><label class="error-label">*<?php echo $errors["rbcc-notnumber"]; ?></label><br> <?php endif; ?>


                    <a id="again-button" href="/parameters/">Pokušajte ponovno</a>
                </div>
            </div>

        <?php else:?>

        <div id="p1">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Korak 1. Arterijska hipertenzija</h3>
                </div>
                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite sistolički i dijastolički krvni tlak:</h3>
                </div>

                <input step="any" type="number" name="bp-sys" placeholder="sistolički krvni tlak">
                <input  step="any" type="number" name="bp-dia" placeholder="dijastolički krvni tlak"><br>

                <div class="btn-group" role="group" aria-label="...">
                    <label for='step2' class="continue">
                        <div>&#187;</div>
                    </label>
                </div>
            </div>
        </div>

        <div id="p2">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Korak 2. Hematološki čimbenici</h3>
                </div>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite broj eritrocita:</h3>
                </div>

                <input step="any" type="number" name="rbc" placeholder="Enter value"><br>


                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite hemoglobin:</h3>
                </div>

                <input step="any" type="number" name="hemo" placeholder="Enter value"><br>

                <div class="btn-group" role="group" aria-label="...">
                    <label for='step2' class="back">
                        <div>&#171;</div>
                    </label>

                    <label for='step3' class="continue">
                        <div>&#187;</div>
                    </label>

                </div>
            </div>
        </div>

        <div id="p3">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Korak 3. Biokemijski čimbenici</h3>
                </div>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite koncentraciju šečera:</h3>
                </div>

                <input step="any" type="number" name="su" placeholder="Enter value"><br>


                <div class="page-heading">
                <h3 class="page-text">Molimo upišite koncentraciju ureje:</h3>
            </div>

            <input step="any" type="number" name="bu" placeholder="Enter value"><br>

            <div class="page-heading">
                <h3 class="page-text">Molimo upišite koncentraciju kreatinina:</h3>
            </div>

            <input step="any" type="number" name="sc" placeholder="Enter value"><br>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite natrij:</h3>
                </div>

                <input step="any" type="number" name="sod" placeholder="Enter value"><br>


                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite kalij:</h3>
                </div>

                <input step="any" type="number" name="pot" placeholder="Enter value"><br>

                <div class="btn-group" role="group" aria-label="...">
                    <label for='step3' class="back">
                        <div>&#171;</div>
                    </label>


                    <label for='step4' class="continue">
                        <div>&#187;</div>
                    </label>

                </div>
            </div>
        </div>

        <div id="p4">
            <div class="panel">
                <div class="panel-heading">
                    <h3>Korak 4. Čimbenici urina</h3>
                </div>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite specifičnu težinu urina:</h3>
                </div>

                <input step="any" type="number" name="sg" placeholder="1.010"><br>


                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite albumin:</h3>
                </div>

                <input step="any" type="number" name="al" placeholder="Enter value"><br>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite broj leukocita u urinu:</h3>
                </div>

                <input step="any" type="number" name="wbcc" placeholder="Enter value"><br>

                <div class="page-heading">
                    <h3 class="page-text">Molimo upišite broj eritrocita u urinu:</h3>
                </div>

                <input step="any" type="number" name="rbcc" placeholder="Enter value"><br>

                <div class="btn-group" role="group" aria-label="...">
                    <label for='step4' class="back">
                        <div>&#171;</div>
                    </label>

                    <div class="submit">
                    <button type="submit" name="check-submit">Provjeri</button>
                    </div>

                </div>
            </div>
        </div>

        </div>

          <?php endif;?>
    </form>
</div>


<?php require '../app/Views/foot.phtml' ?>
