<?php require '../app/Views/header.phtml' ?>

<div class="login-form">
    <form class="signup-form" action="/login/login" method="POST">
        <input type="text" name="usernameoremail" placeholder="Korisničko ime ili email adresa"><br>
        <input type="password" name="password" placeholder="Lozinka"><br>
        <input id="remember" type="checkbox" name="remember"> <a id="remembertext">Zapamti me</a><br>
        <button type="submit" name="login-submit">Prijava</button>
       </form>
    <div class="notmember"><p>Niste član? <a href="/registration/index">Registrirajte se</a>!</p></div>
</div>

<?php require '../app/Views/footer.phtml' ?>
