<!DOCTYPE html>
<html>
<head>
    <title>Home page</title>
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>

<body>

    <nav>
        <ul>
            <li><a class="nav_button" href="/home/">Home</a></li>
            <li><a class="nav_button" href="/home/">Generate</a></li>
            <li><a class="nav_button" href="/home/">Visual</a></li>
            <li><a class="nav_button" href="/home/">Account</a></li>
            <li><a class="nav_button" href="/home/">Log out</a></li>
            </div>
        </ul>
    </nav>

